[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip"]

[phases.build]
cmds = [
    "cd backend && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt",
    "cd frontend && npm install && npm run build"
]

[phases.start]
cmd = "cd backend && source venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 8000"

